// Generated by gencpp from file topic_day4_pkg/person.msg
// DO NOT EDIT!


#ifndef TOPIC_DAY4_PKG_MESSAGE_PERSON_H
#define TOPIC_DAY4_PKG_MESSAGE_PERSON_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace topic_day4_pkg
{
template <class ContainerAllocator>
struct person_
{
  typedef person_<ContainerAllocator> Type;

  person_()
    : nama()
    , usia(0)
    , tinggi(0.0)
    , kehadiran(false)  {
    }
  person_(const ContainerAllocator& _alloc)
    : nama(_alloc)
    , usia(0)
    , tinggi(0.0)
    , kehadiran(false)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _nama_type;
  _nama_type nama;

   typedef int64_t _usia_type;
  _usia_type usia;

   typedef double _tinggi_type;
  _tinggi_type tinggi;

   typedef uint8_t _kehadiran_type;
  _kehadiran_type kehadiran;





  typedef boost::shared_ptr< ::topic_day4_pkg::person_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::topic_day4_pkg::person_<ContainerAllocator> const> ConstPtr;

}; // struct person_

typedef ::topic_day4_pkg::person_<std::allocator<void> > person;

typedef boost::shared_ptr< ::topic_day4_pkg::person > personPtr;
typedef boost::shared_ptr< ::topic_day4_pkg::person const> personConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::topic_day4_pkg::person_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::topic_day4_pkg::person_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::topic_day4_pkg::person_<ContainerAllocator1> & lhs, const ::topic_day4_pkg::person_<ContainerAllocator2> & rhs)
{
  return lhs.nama == rhs.nama &&
    lhs.usia == rhs.usia &&
    lhs.tinggi == rhs.tinggi &&
    lhs.kehadiran == rhs.kehadiran;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::topic_day4_pkg::person_<ContainerAllocator1> & lhs, const ::topic_day4_pkg::person_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace topic_day4_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::topic_day4_pkg::person_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::topic_day4_pkg::person_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::topic_day4_pkg::person_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::topic_day4_pkg::person_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::topic_day4_pkg::person_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::topic_day4_pkg::person_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::topic_day4_pkg::person_<ContainerAllocator> >
{
  static const char* value()
  {
    return "642dd92b70eae635c30acd8224032ab7";
  }

  static const char* value(const ::topic_day4_pkg::person_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x642dd92b70eae635ULL;
  static const uint64_t static_value2 = 0xc30acd8224032ab7ULL;
};

template<class ContainerAllocator>
struct DataType< ::topic_day4_pkg::person_<ContainerAllocator> >
{
  static const char* value()
  {
    return "topic_day4_pkg/person";
  }

  static const char* value(const ::topic_day4_pkg::person_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::topic_day4_pkg::person_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string nama\n"
"int64 usia\n"
"float64 tinggi\n"
"bool kehadiran\n"
;
  }

  static const char* value(const ::topic_day4_pkg::person_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::topic_day4_pkg::person_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.nama);
      stream.next(m.usia);
      stream.next(m.tinggi);
      stream.next(m.kehadiran);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct person_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::topic_day4_pkg::person_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::topic_day4_pkg::person_<ContainerAllocator>& v)
  {
    s << indent << "nama: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.nama);
    s << indent << "usia: ";
    Printer<int64_t>::stream(s, indent + "  ", v.usia);
    s << indent << "tinggi: ";
    Printer<double>::stream(s, indent + "  ", v.tinggi);
    s << indent << "kehadiran: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.kehadiran);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TOPIC_DAY4_PKG_MESSAGE_PERSON_H
