// Generated by gencpp from file tutorial2/person_data.msg
// DO NOT EDIT!


#ifndef TUTORIAL2_MESSAGE_PERSON_DATA_H
#define TUTORIAL2_MESSAGE_PERSON_DATA_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace tutorial2
{
template <class ContainerAllocator>
struct person_data_
{
  typedef person_data_<ContainerAllocator> Type;

  person_data_()
    : name()
    , age(0)
    , home()  {
    }
  person_data_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , age(0)
    , home(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _name_type;
  _name_type name;

   typedef int64_t _age_type;
  _age_type age;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _home_type;
  _home_type home;





  typedef boost::shared_ptr< ::tutorial2::person_data_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tutorial2::person_data_<ContainerAllocator> const> ConstPtr;

}; // struct person_data_

typedef ::tutorial2::person_data_<std::allocator<void> > person_data;

typedef boost::shared_ptr< ::tutorial2::person_data > person_dataPtr;
typedef boost::shared_ptr< ::tutorial2::person_data const> person_dataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tutorial2::person_data_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tutorial2::person_data_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::tutorial2::person_data_<ContainerAllocator1> & lhs, const ::tutorial2::person_data_<ContainerAllocator2> & rhs)
{
  return lhs.name == rhs.name &&
    lhs.age == rhs.age &&
    lhs.home == rhs.home;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::tutorial2::person_data_<ContainerAllocator1> & lhs, const ::tutorial2::person_data_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace tutorial2

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::tutorial2::person_data_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tutorial2::person_data_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tutorial2::person_data_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tutorial2::person_data_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tutorial2::person_data_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tutorial2::person_data_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tutorial2::person_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "249a937db1a1921606ac75cb2cec8dca";
  }

  static const char* value(const ::tutorial2::person_data_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x249a937db1a19216ULL;
  static const uint64_t static_value2 = 0x06ac75cb2cec8dcaULL;
};

template<class ContainerAllocator>
struct DataType< ::tutorial2::person_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tutorial2/person_data";
  }

  static const char* value(const ::tutorial2::person_data_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tutorial2::person_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string name\n"
"int64 age\n"
"string home\n"
;
  }

  static const char* value(const ::tutorial2::person_data_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tutorial2::person_data_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.age);
      stream.next(m.home);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct person_data_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tutorial2::person_data_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tutorial2::person_data_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.name);
    s << indent << "age: ";
    Printer<int64_t>::stream(s, indent + "  ", v.age);
    s << indent << "home: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.home);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TUTORIAL2_MESSAGE_PERSON_DATA_H
