// Generated by gencpp from file tutorial2/ProductTwoIntsRequest.msg
// DO NOT EDIT!


#ifndef TUTORIAL2_MESSAGE_PRODUCTTWOINTSREQUEST_H
#define TUTORIAL2_MESSAGE_PRODUCTTWOINTSREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace tutorial2
{
template <class ContainerAllocator>
struct ProductTwoIntsRequest_
{
  typedef ProductTwoIntsRequest_<ContainerAllocator> Type;

  ProductTwoIntsRequest_()
    : a(0)
    , b(0)  {
    }
  ProductTwoIntsRequest_(const ContainerAllocator& _alloc)
    : a(0)
    , b(0)  {
  (void)_alloc;
    }



   typedef int64_t _a_type;
  _a_type a;

   typedef int64_t _b_type;
  _b_type b;





  typedef boost::shared_ptr< ::tutorial2::ProductTwoIntsRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tutorial2::ProductTwoIntsRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ProductTwoIntsRequest_

typedef ::tutorial2::ProductTwoIntsRequest_<std::allocator<void> > ProductTwoIntsRequest;

typedef boost::shared_ptr< ::tutorial2::ProductTwoIntsRequest > ProductTwoIntsRequestPtr;
typedef boost::shared_ptr< ::tutorial2::ProductTwoIntsRequest const> ProductTwoIntsRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tutorial2::ProductTwoIntsRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tutorial2::ProductTwoIntsRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::tutorial2::ProductTwoIntsRequest_<ContainerAllocator1> & lhs, const ::tutorial2::ProductTwoIntsRequest_<ContainerAllocator2> & rhs)
{
  return lhs.a == rhs.a &&
    lhs.b == rhs.b;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::tutorial2::ProductTwoIntsRequest_<ContainerAllocator1> & lhs, const ::tutorial2::ProductTwoIntsRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace tutorial2

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::tutorial2::ProductTwoIntsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tutorial2::ProductTwoIntsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tutorial2::ProductTwoIntsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tutorial2::ProductTwoIntsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tutorial2::ProductTwoIntsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tutorial2::ProductTwoIntsRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tutorial2::ProductTwoIntsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "36d09b846be0b371c5f190354dd3153e";
  }

  static const char* value(const ::tutorial2::ProductTwoIntsRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x36d09b846be0b371ULL;
  static const uint64_t static_value2 = 0xc5f190354dd3153eULL;
};

template<class ContainerAllocator>
struct DataType< ::tutorial2::ProductTwoIntsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tutorial2/ProductTwoIntsRequest";
  }

  static const char* value(const ::tutorial2::ProductTwoIntsRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tutorial2::ProductTwoIntsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 a\n"
"int64 b\n"
;
  }

  static const char* value(const ::tutorial2::ProductTwoIntsRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tutorial2::ProductTwoIntsRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.a);
      stream.next(m.b);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ProductTwoIntsRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tutorial2::ProductTwoIntsRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tutorial2::ProductTwoIntsRequest_<ContainerAllocator>& v)
  {
    s << indent << "a: ";
    Printer<int64_t>::stream(s, indent + "  ", v.a);
    s << indent << "b: ";
    Printer<int64_t>::stream(s, indent + "  ", v.b);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TUTORIAL2_MESSAGE_PRODUCTTWOINTSREQUEST_H
