// Generated by gencpp from file tutorial2/ProductTwoInts.msg
// DO NOT EDIT!


#ifndef TUTORIAL2_MESSAGE_PRODUCTTWOINTS_H
#define TUTORIAL2_MESSAGE_PRODUCTTWOINTS_H

#include <ros/service_traits.h>


#include <tutorial2/ProductTwoIntsRequest.h>
#include <tutorial2/ProductTwoIntsResponse.h>


namespace tutorial2
{

struct ProductTwoInts
{

typedef ProductTwoIntsRequest Request;
typedef ProductTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ProductTwoInts
} // namespace tutorial2


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tutorial2::ProductTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::tutorial2::ProductTwoInts&) { return value(); }
};

template<>
struct DataType< ::tutorial2::ProductTwoInts > {
  static const char* value()
  {
    return "tutorial2/ProductTwoInts";
  }

  static const char* value(const ::tutorial2::ProductTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::tutorial2::ProductTwoIntsRequest> should match
// service_traits::MD5Sum< ::tutorial2::ProductTwoInts >
template<>
struct MD5Sum< ::tutorial2::ProductTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tutorial2::ProductTwoInts >::value();
  }
  static const char* value(const ::tutorial2::ProductTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tutorial2::ProductTwoIntsRequest> should match
// service_traits::DataType< ::tutorial2::ProductTwoInts >
template<>
struct DataType< ::tutorial2::ProductTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::tutorial2::ProductTwoInts >::value();
  }
  static const char* value(const ::tutorial2::ProductTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tutorial2::ProductTwoIntsResponse> should match
// service_traits::MD5Sum< ::tutorial2::ProductTwoInts >
template<>
struct MD5Sum< ::tutorial2::ProductTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tutorial2::ProductTwoInts >::value();
  }
  static const char* value(const ::tutorial2::ProductTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tutorial2::ProductTwoIntsResponse> should match
// service_traits::DataType< ::tutorial2::ProductTwoInts >
template<>
struct DataType< ::tutorial2::ProductTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::tutorial2::ProductTwoInts >::value();
  }
  static const char* value(const ::tutorial2::ProductTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TUTORIAL2_MESSAGE_PRODUCTTWOINTS_H
