(cl:defpackage service_day4_pkg-srv
  (:use )
  (:export
   "COUNTMAGNITUDE"
   "<COUNTMAGNITUDE-REQUEST>"
   "COUNTMAGNITUDE-REQUEST"
   "<COUNTMAGNITUDE-RESPONSE>"
   "COUNTMAGNITUDE-RESPONSE"
  ))

