// Generated by gencpp from file demo_pkg/AddTwoIntsResponse.msg
// DO NOT EDIT!


#ifndef DEMO_PKG_MESSAGE_ADDTWOINTSRESPONSE_H
#define DEMO_PKG_MESSAGE_ADDTWOINTSRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace demo_pkg
{
template <class ContainerAllocator>
struct AddTwoIntsResponse_
{
  typedef AddTwoIntsResponse_<ContainerAllocator> Type;

  AddTwoIntsResponse_()
    : sumvalue(0)  {
    }
  AddTwoIntsResponse_(const ContainerAllocator& _alloc)
    : sumvalue(0)  {
  (void)_alloc;
    }



   typedef int64_t _sumvalue_type;
  _sumvalue_type sumvalue;





  typedef boost::shared_ptr< ::demo_pkg::AddTwoIntsResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::demo_pkg::AddTwoIntsResponse_<ContainerAllocator> const> ConstPtr;

}; // struct AddTwoIntsResponse_

typedef ::demo_pkg::AddTwoIntsResponse_<std::allocator<void> > AddTwoIntsResponse;

typedef boost::shared_ptr< ::demo_pkg::AddTwoIntsResponse > AddTwoIntsResponsePtr;
typedef boost::shared_ptr< ::demo_pkg::AddTwoIntsResponse const> AddTwoIntsResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::demo_pkg::AddTwoIntsResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::demo_pkg::AddTwoIntsResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::demo_pkg::AddTwoIntsResponse_<ContainerAllocator1> & lhs, const ::demo_pkg::AddTwoIntsResponse_<ContainerAllocator2> & rhs)
{
  return lhs.sumvalue == rhs.sumvalue;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::demo_pkg::AddTwoIntsResponse_<ContainerAllocator1> & lhs, const ::demo_pkg::AddTwoIntsResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace demo_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::demo_pkg::AddTwoIntsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::demo_pkg::AddTwoIntsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::demo_pkg::AddTwoIntsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::demo_pkg::AddTwoIntsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::demo_pkg::AddTwoIntsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::demo_pkg::AddTwoIntsResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::demo_pkg::AddTwoIntsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "51b79b1ce1ac22a0e9edc56557c575f1";
  }

  static const char* value(const ::demo_pkg::AddTwoIntsResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x51b79b1ce1ac22a0ULL;
  static const uint64_t static_value2 = 0xe9edc56557c575f1ULL;
};

template<class ContainerAllocator>
struct DataType< ::demo_pkg::AddTwoIntsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "demo_pkg/AddTwoIntsResponse";
  }

  static const char* value(const ::demo_pkg::AddTwoIntsResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::demo_pkg::AddTwoIntsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 sumvalue\n"
;
  }

  static const char* value(const ::demo_pkg::AddTwoIntsResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::demo_pkg::AddTwoIntsResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sumvalue);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AddTwoIntsResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::demo_pkg::AddTwoIntsResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::demo_pkg::AddTwoIntsResponse_<ContainerAllocator>& v)
  {
    s << indent << "sumvalue: ";
    Printer<int64_t>::stream(s, indent + "  ", v.sumvalue);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DEMO_PKG_MESSAGE_ADDTWOINTSRESPONSE_H
